baseURL = "https://mandreyel.github.io/"
languageCode = "en-us"
title = "mandreyel's blog"
theme = "hugo_theme_pickles"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  github = "mandreyel"
  gitlab = "mandreyel"

  author = "mandreyel"
  #authorwebsite = "example.com"
  #avatar = "/path/to/avatar"
  contact = "mandreyel@protonmail.com"
  bio = "it's me"

  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "TODO change this"

  # Logo image. This is displayed ogp image.
  #logo = "/path/to/logo"
  #favicon = "/path/to/favicon"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"

