#baseUrl = "https://mandreyel.github.io/"
baseUrl = "/"
languageCode = "en-us"
theme = "smol"
#theme = "cactus"
title = "mandreyel's blog"
copyright = ""
paginate = 20

[params]
colortheme = "dark" # dark, light, white, or classic
subtitle = "...this space is growing..."

#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1

#[[menu.main]]
#name = "Posts"
#url = "/posts"
#weight = 2

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 3

# TODO: add about section
#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 4

#[params]
  #subtitle = "thoughts on software, projects, Rust"

[menu]
# Header
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

# Footer
[[menu.footer]]
name = "Github"
url = "https://github.com/mandreyel"
weight = 1
