baseurl = "/"
title = "mandreyel's site"
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"

disqusShortname = ""

[author]
  name = "mandreyel"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "thoughst on stuff"

[params]
  github = "mandreyel"
  gitlab = "mandreyel"
  #twitter = "twitter id"
  #linkedin = "linkedin id"
  #email = "myemail"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#99cc66"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
